// theme.js — IDENTEE design tokens (bold editorial: white + gold blocks + ink)

export const THEME = {
  bg: "#FFFFFF",
  surface: "#FFFFFF",
  surface2: "#F7F4EC",
  border: "#EAE3CF",
  borderLight: "#DED2AC",
  gold: "#C9A24B",
  goldBright: "#E8B94D",
  goldBlock: "#F0C24C",
  goldDeep: "#9C7A2E",
  goldBg: "#C9A24B18",
  goldBorder: "#C9A24B4D",
  ink: "#141110",
  inkSoft: "#241B14",
  accent: "#C0392B",
  accentBg: "#C0392B14",
  accentBorder: "#C0392B44",
  text: "#141110",
  textMuted: "#6B6559",
  textFaint: "#A39C8C",
  danger: "#C0392B",
  dangerBg: "#C0392B14",
  dangerBorder: "#C0392B44",
  fontDisplay: "'Cormorant Garamond', serif",
  fontBody: "'Inter', sans-serif",
  shadow: "0 4px 20px rgba(20,17,16,0.08)",
};

export const getLabelStyle = (theme = THEME) => ({
  fontSize: 11,
  fontWeight: 600,
  color: theme.textMuted,
  letterSpacing: "0.08em",
  textTransform: "uppercase",
  fontFamily: theme.fontBody,
});

export const getInputStyle = (theme = THEME) => ({
  width: "100%",
  background: theme.surface2,
  border: `1px solid ${theme.border}`,
  borderRadius: 7,
  padding: "8px 11px",
  color: theme.text,
  fontSize: 13,
  fontFamily: theme.fontBody,
  outline: "none",
  boxSizing: "border-box",
  transition: "border-color 0.15s, box-shadow 0.15s",
});

export const labelStyle = {
  fontSize: 11,
  fontWeight: 600,
  color: THEME.textMuted,
  letterSpacing: "0.08em",
  textTransform: "uppercase",
  fontFamily: THEME.fontBody,
};

export const inputStyle = {
  width: "100%",
  background: THEME.surface2,
  border: `1px solid ${THEME.border}`,
  borderRadius: 7,
  padding: "8px 11px",
  color: THEME.text,
  fontSize: 13,
  fontFamily: THEME.fontBody,
  outline: "none",
  boxSizing: "border-box",
  transition: "border-color 0.15s, box-shadow 0.15s",
};

export const sectionHeading = {
  fontSize: 13,
  fontWeight: 600,
  color: THEME.goldDeep,
  textTransform: "uppercase",
  letterSpacing: "0.12em",
  fontFamily: THEME.fontBody,
  margin: "30px 0 16px",
  paddingBottom: 10,
  borderBottom: `1px solid ${THEME.border}`,
  display: "flex",
  alignItems: "center",
  gap: 8,
};

export const SIZE_CHARTS = {
  "Round Neck": [
    "4-6",
    "6-8",
    "8-10",
    "10-12",
    "12-14",
    "14-16",
    "S",
    "M",
    "L",
    "XL",
    "XXL",
  ],
  Oversized: [
    "4-6",
    "6-8",
    "8-10",
    "10-12",
    "12-14",
    "14-16",
    "S",
    "M",
    "L",
    "XL",
    "XXL",
  ],
  Hoodie: [
    "4-6",
    "6-8",
    "8-10",
    "10-12",
    "12-14",
    "14-16",
    "S",
    "M",
    "L",
    "XL",
    "XXL",
  ],
  Sweatshirt: [
    "4-6",
    "6-8",
    "8-10",
    "10-12",
    "12-14",
    "14-16",
    "S",
    "M",
    "L",
    "XL",
    "XXL",
  ],
  Polo: ["10-12", "12-14", "14-16", "S", "M", "L", "XL", "XXL"],
};

export const PRODUCT_STYLES = Object.keys(SIZE_CHARTS);
